"""
Add minigrid_id column to mesure_minigrid
"""
revision = '20231006_add_minigrid_id_to_mesure_minigrid'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    op.add_column('mesure_minigrid', sa.Column('minigrid_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_mesure_minigrid_minigrid', 'mesure_minigrid', 'mini_grid', ['minigrid_id'], ['id'], ondelete='CASCADE')

#def downgrade():
    #op.drop_constraint('fk_mesure_minigrid_minigrid', 'mesure_minigrid', type_='foreignkey')
    #op.drop_column('mesure_minigrid', 'minigrid_id')